# Generated by Django 4.0.2 on 2022-02-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HierarchicalModelMixin',
        ),
    ]
