# Generated by Django 4.0.2 on 2022-02-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
