# Generated by Django 4.0.2 on 2022-02-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationalunit_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.organizationalunit'),
        ),
    ]
